name: bug report
description: report a bug or issue
title: "[bug]: "
labels: ["bug"]

body:
  - type: input
    id: platform
    attributes:
      label: Platform/module name (if applicable)
      description:
        Which platform were you downloading from? Leave blank if not related to
        a specific platform.
      placeholder: "Bunkr, PixelDrain, Cyberdrop, GoFile, etc."
    validations:
      required: false

  - type: textarea
    id: url
    attributes:
      label: Problem URL(s) (if applicable)
      description:
        The specific URL(s) causing issues. Leave blank if not related to
        specific URLs.
      placeholder: "Paste the exact URL(s) you were trying to download"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: What went wrong and what did you expect?
      placeholder: "Description of the bug and expected behavior"
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error output
      description: Full error message (enable DEBUG logging if possible)
      placeholder: "Paste complete error message and stack trace"
      render: shell
    validations:
      required: false

  - type: input
    id: python-version
    attributes:
      label: Python version
      placeholder: "3.13.7"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "Windows 11, macOS 14, Ubuntu 22.04"
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues for duplicates
          required: true
        - label: I tested with the latest version
          required: true
