name: feature request
description: Suggest a new feature or enhancement
title: '[feature]: '
labels: ['enhancement']

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve?
      placeholder: "Describe the problem or limitation you're facing"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: What would you like to see implemented?
      placeholder: 'Describe your ideal solution'
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: How would you use this feature?
      placeholder: 'Provide specific examples of usage'
    validations:
      required: true
